### ISSUE TITLE
Welcome

### ISSUE THREAD

**Issue by bitoiu** [bitoiu/git-workshop-psc#1]
Hey @goncalossilva,

I was thinking of using this issue for participants to introduce themselves and ask issues before and during the brownbag. Another option would be a Slack chat room. Issues have worked well before so can you send this issue link for the people joining?

It would be nice if each participant comments on this issue and adds:
- First name
- A favourite movie OR book (ice breaker :wink:)
- What do you want to take out of the workshop?

Do you agree @goncalossilva?

**Comment by bitoiu** [comment]
Hey, I'm one of your trainers for the workshop:
 - Vitor
 - Movie: [Requiem for a Dream](http://www.imdb.com/title/tt0180093/), Book: [Flashboys](https://www.goodreads.com/book/show/24724602-flash-boys)
 - I hope that people feel excited about learning a new VCS tool or get some insight into best practices. Hopefully people will leave the session fulfilled, that's all I can ask :octocat::heart:

**Comment by goncalossilva** [comment]
Sounds great @bitoiu! I'll send the link as soon as registrations close.

As for me, I'll be helping Vitor in this workshop!
- Gonçalo
- Movie / book: There's just too many. Since we're all tech people, I think you'll enjoy [The Dark Knight](http://www.imdb.com/title/tt0468569/) very much if you haven't watched it already 😄 
- I'm hoping participants will come out of the workshop much more familiar with Git and able to teach others what they've learned. VCS is extremely important in tech, but often not covered deeply in college.

**Comment by bitoiu** [comment]
Hey @goncalossilva, did you share the link with the participants? If so, folks are super shy :smile:

![shy](http://s2.quickmeme.com/img/d6/d6292b279f8812d066595ce17691a193a0ba74b81c9ee6307fad8de9ad66e57e.jpg)

**Comment by goncalossilva** [comment]
Haha, not yet! An email is going out today 👍

**Comment by Daniel-C-Dias** [comment]
Hello, I'm one the participants in the workshop:

- My name is Daniel, nice to meet you all.
- As for my favorite movie, hummm there so many so I'll say Star Wars: The Empire Strikes Back and I'll also throw in Pacific Rim, because that movie deserves love ;)
- I don't know much about GitHub and I'm only a beginner at this coding stuff, but I'm hoping to become a lot more familiar with a new tool and enrich my "ability tree"

Hope to see everybody Friday!

**Comment by JCacho** [comment]
Hi guys, I'm also one of the participants :)

- João, but people call me Cacho
- I have no FAVORITE movie but I love almost all Tolkien and Verne books
- I really don't know much about GitHub but I can code in a few languages and I'm a huge fan of embedded systems (mostly arduino and rpi)

See you soon guys!!

**Comment by Daniel-C-Dias** [comment]
Hello, I have some questions. When I download the GitHub desktop edition it created 2 shortcuts: GitHub and Git Shell but the Git Shell doesn't reconize the $ symbol and on the "Cloning Tuturial" it asks me to open a Git Bash that I don't see. Is it the same as the Git Shell?

**Comment by goncalossilva** [comment]
@Daniel-C-Dias In "shell speak", the "$" symbol is used to symbolize the beginning of the line — you're not supposed to paste it as well. Paste everything _after_ it! As for the second question, I'd assume Git Bash is the same thing as Git Shell, though I'm not 100% sure. @bitoiu definitely knows the answer to this one 😊

**Comment by bitoiu** [comment]
GitBash is the same as GitShell. GitBash is a standalone product that offers pretty much the same thing: https://git-for-windows.github.io/. It not only brings Git but most of the unix command line tools.

Windows can be a bit tricky but I've heard or read somewhere they are shipping a decent shell in one of their most recent OS versions. That took them some time 😬 

:octocat::heart:

**Comment by Daniel-C-Dias** [comment]
Thanks @bitoiu and @goncalossilva. I think I'm ready for Friday now. See you soon!

**Comment by spkkya** [comment]
https://github.com/spkkya/psc16

**Comment by bitoiu** [comment]
https://github.com/bitoiu/psc16

**Comment by SirRibeiro** [comment]
https://github.com/SirRibeiro/psc16

**Comment by TheMith** [comment]
https://github.com/TheMith/test

**Comment by JCacho** [comment]
https://github.com/JCacho/PSC16

**Comment by G-Pereira** [comment]
https://github.com/G-Pereira/psc16

**Comment by Daniel-C-Dias** [comment]
https://github.com/Daniel-C-Dias/psc16.git

**Comment by nmelof** [comment]
https://github.com/nmelof/vavavoom

**Comment by euricoteles** [comment]
https://github.com/euricoteles/workshop_psc2016/

**Comment by martinspedr0** [comment]
https://github.com/martinspedr0/PSC2016-GIT_Workshop.git

**Comment by pedroosorio** [comment]
https://github.com/pedroosorio/PSC16.git

**Comment by JoseLuisMartins** [comment]
https://github.com/JoseLuisMartins/psc16Workshop.git

**Comment by ghostpick** [comment]
https://github.com/ghostpick/testes

**Comment by jresende** [comment]
https://github.com/jresende/teste

**Comment by patricia93sousa** [comment]
https://github.com/patricia93sousa/psc16

**Comment by a-gradim** [comment]
https://github.com/a-gradim/git_workshop_2016

**Comment by bitoiu** [comment]
Thank you everyone for so many contributions and so much good work :octocat::heart:
