### ISSUE TITLE
Contacto

### ISSUE THREAD

**Issue by pedroosorio** [bitoiu/git-workshop-psc#2]
Boas !

Participei no workshop de Git no PSC16 e tinha uma dúvida. Não sabendo como te contactar, isto deve servir :+1:  ! Se eu criar um repositorio localmente, com o _git init_ eu tenho acesso localmente a todos os commits com o _git log_ e posso posteriormente meter o repositorio local num repositiorio na cloud. Até aqui, tudo bem ! A pergunta é : como fazer o inverso ? Como "clonar" um repositório meu que esteja online e ter também a pasta .git, para ter localmente o histórico todo que estava guardado online ?

**Comment by goncalossilva** [comment]
Viva @pedroosorio! Quase respondeste a ti próprio 😊 O comando é `git clone <repo>` e faz exactamente o que descreveste.

**Comment by bitoiu** [comment]
Boa @goncalossilva 👍

**Comment by pedroosorio** [comment]
Thanks ! Já testei, como a pasta .git estava hidden, não dei por ela ! Obrigado pelo workshop, foi excelente !

Abraço

**Comment by bitoiu** [comment]
Obrigado por teres vindo @pedroosorio :smile:

Cuidado com esses pull requests 😆
